apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    crossplane.io/external-name: ${Rand.RFC1123Subdomain}
    testing.upbound.io/example-name: input_bucket_label
  name: ${Rand.RFC1123Subdomain}
spec:
  forProvider:
    forceDestroy: true
    region: us-west-1