apiVersion: batch/v1
kind: Job
metadata:
  name: see-db-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: see-db
          image: postgres:12
          command: ['psql']
          args: ['-c', 'SELECT current_database();']
          env:
          - name: PGDATABASE
            value: postgres
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: example-dbinstance-out
                key: endpoint
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: example-dbinstance-out
                key: username
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: example-dbinstance-out
                key: password
          - name: PGPORT
            valueFrom:
              secretKeyRef:
                name: example-dbinstance-out
                key: port
      restartPolicy: Never
  backoffLimit: 4
